import os

# Ruta  a la base de datos
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, 'database', 'tienda_juegos.db')

# Flask
FLASK_CONFIG = {
    'SECRET_KEY': 'clave_secreta_123',  # Para sesiones
    'HOST': '0.0.0.0',
    'PORT': 5001,
    'DEBUG': True
}

#   chatbot
CHATBOT_CONFIG = {
    'MAX_JUEGOS_RESULTADO': 5,   
    'STOPWORDS': [
        'quiero', 'busco', 'el', 'la', 'hay', 'tienes', 'dame',
        'cuanto', 'cuesta', 'cuestan', 'vale', 'valen', 'precio', 'un', 'una', 'de', 'que',
        'juegos', 'juego', 'para', 'versiones', 'version', 'edicion', 'ediciones',
        'cobras', 'cobran', 'pides', 'piden', 'pones', 'ponen', 'sale', 'salen',
        'esta', 'estan', 'como', 'me', 'lo', 'por', 'a', 'es', 'tiene', 'tienen',
        'cuanto', 'cuantos', 'cual', 'que', 'das', 'dan'
    ]
}

# variaciones de lo que el usuario escribe y lo que es en la base de datos 
PLATAFORMA_MAP = {
    'ps5': 'PlayStation 5',
    'ps 5': 'PlayStation 5',
    'playstation5': 'PlayStation 5',
    'playstation 5': 'PlayStation 5',
    'playstation': 'PlayStation 5',
    'play5': 'PlayStation 5',
    'play station': 'PlayStation 5',
    'sony': 'PlayStation 5',
    'xbox': 'Xbox Series X',
    'xbox series x': 'Xbox Series X',
    'xbox series': 'Xbox Series X',
    'series x': 'Xbox Series X',
    'xsx': 'Xbox Series X',
    'microsoft xbox': 'Xbox Series X',
    'switch': 'Nintendo Switch',
    'nintendo switch': 'Nintendo Switch',
    'nintendo': 'Nintendo Switch',
    'switch lite': 'Nintendo Switch',
    'switch oled': 'Nintendo Switch',
    'ns': 'Nintendo Switch',
    'pc': 'PC',
    'windows': 'PC',
    'steam': 'PC',
    'ordenador': 'PC',
    'computadora': 'PC',
    'computador': 'PC',
    'mac': 'PC',
}

# Plataformas que reconocemos pero para las que no tenemos juegos
PLATAFORMAS_SIN_JUEGOS = {
    
    'ps4': 'PlayStation 4',
    'ps 4': 'PlayStation 4',
    'playstation4': 'PlayStation 4',
    'playstation 4': 'PlayStation 4',
    'ps3': 'PlayStation 3',
    'ps 3': 'PlayStation 3',
    'playstation3': 'PlayStation 3',
    'playstation 3': 'PlayStation 3',
    'ps2': 'PlayStation 2',
    'ps 2': 'PlayStation 2',
    'playstation2': 'PlayStation 2',
    'playstation 2': 'PlayStation 2',
    'ps1': 'PlayStation 1',
    'ps 1': 'PlayStation 1',
    'psx': 'PlayStation 1',
    'psp': 'PSP',
    'vita': 'PS Vita',
    'psvita': 'PS Vita',
    'ps vita': 'PS Vita',
    'xbox one': 'Xbox One',
    'xbone': 'Xbox One',
    'xbox 360': 'Xbox 360',
    'xbox360': 'Xbox 360',
    'xbox original': 'Xbox Original',
    'wii': 'Nintendo Wii',
    'wiiu': 'Nintendo Wii U',
    'wii u': 'Nintendo Wii U',
    '3ds': 'Nintendo 3DS',
    'nintendo 3ds': 'Nintendo 3DS',
    'ds': 'Nintendo DS',
    'nintendo ds': 'Nintendo DS',
    'gameboy': 'Game Boy',
    'game boy': 'Game Boy',
    'gba': 'Game Boy Advance',
    'n64': 'Nintendo 64',
    'nintendo 64': 'Nintendo 64',
    'gamecube': 'GameCube',
    'snes': 'Super Nintendo',
    'super nintendo': 'Super Nintendo',
    'nes': 'NES',
    'android': 'Android',
    'ios': 'iOS',
    'movil': 'Movil',
    'telefono': 'Movil',
    'tablet': 'Movil',
    'dreamcast': 'Dreamcast',
    'sega': 'Sega',
    'saturn': 'Sega Saturn',
    'mega drive': 'Mega Drive',
    'vr': 'VR',
    'realidad virtual': 'VR',
}

# Géneros 
GENEROS_MAP = {
    'accion': 'Accion',
    'action': 'Accion',
    'aventura': 'Aventura',
    'aventuras': 'Aventura',
    'adventure': 'Aventura',
    'rpg': 'RPG',
    'rol': 'RPG',
    'roleplay': 'RPG',
    'jrpg': 'RPG',
    'mundo abierto': 'Mundo Abierto',
    'open world': 'Mundo Abierto',
    'simulacion': 'Simulacion',
    'simulador': 'Simulacion',
    'simuladores': 'Simulacion',
    'simulation': 'Simulacion',
    'fps': 'FPS',
    'shooter': 'FPS',
    'disparos': 'FPS',
    'tiros': 'FPS',
    'primera persona': 'FPS',
    'estrategia': 'Estrategia',
    'tactica': 'Estrategia',
    'tactico': 'Estrategia',
    'strategy': 'Estrategia',
    'horror': 'Horror',
    'terror': 'Horror',
    'miedo': 'Horror',
    'sustos': 'Horror',
    'casual': 'Casual',
    'relajante': 'Casual',
    'tranquilo': 'Casual',
    'deportes': 'Deportes',
    'deporte': 'Deportes',
    'futbol': 'Deportes',
    'baloncesto': 'Deportes',
    'sports': 'Deportes',
    'basket': 'Deportes',
    'survival': 'Survival',
    'supervivencia': 'Survival',
    'sobrevivencia': 'Survival',
    'battle royale': 'Battle Royale',
    'royale': 'Battle Royale',
    'lucha': 'Lucha',
    'pelea': 'Lucha',
    'peleas': 'Lucha',
    'fighting': 'Lucha',
    'combate': 'Lucha',
    'sandbox': 'Sandbox',
    'construccion': 'Sandbox',
    'construir': 'Sandbox',
    'creativo': 'Sandbox',
    'puzzle': 'Puzzle',
    'puzzles': 'Puzzle',
    'rompecabezas': 'Puzzle',
    'logica': 'Puzzle',
    'plataformas': 'Plataforma',
    'plataforma': 'Plataforma',
    'platformer': 'Plataforma',
    'roguelike': 'Roguelike',
    'roguelite': 'Roguelike',
    'rogue': 'Roguelike',
    'metroidvania': 'Metroidvania',
    'hack and slash': 'Hack and Slash',
    'hack slash': 'Hack and Slash',
    'cartas': 'Cartas',
    'card game': 'Cartas',
    'naipes': 'Cartas',
    'cocina': 'Cocina',
    'cooking': 'Cocina',
    'chef': 'Cocina',
    'musica': 'Musica',
    'music': 'Musica',
    'ritmo': 'Musica',
    'rhythm': 'Musica',
    'mesa': 'Mesa',
    'board game': 'Mesa',
    'tablero': 'Mesa',
    'educativo': 'Educativo',
    'educacion': 'Educativo',
    'aprender': 'Educativo',
    'animales': 'Animales',
    'mascotas': 'Animales',
    'terror psicologico': 'Terror Psicologico',
    'sigilo': 'Sigilo',
    'stealth': 'Sigilo',
    'novela visual': 'Novela Visual',
    'visual novel': 'Novela Visual',
    'anime': 'Anime',
    'manga': 'Anime',
    'defensa de torres': 'Defensa de Torres',
    'tower defense': 'Defensa de Torres',
    'moba': 'MOBA',
    'gestion': 'Gestion',
    'administracion': 'Gestion',
    'city builder': 'Gestion',
    'construccion ciudad': 'Gestion',
    'mmo': 'MMO',
    'mmorpg': 'MMO',
    'multijugador masivo': 'MMO',
    'carreras': 'Carreras',
    'racing': 'Carreras',
    'coches': 'Carreras',
    'formula': 'Carreras',
    'f1': 'Carreras',
    'accion aventura': 'Accion',
    'action adventure': 'Accion',
    'tercera persona': 'Accion',
    'soulslike': 'RPG',
    'souls': 'RPG',
    'dark souls': 'RPG',
    'rpg de accion': 'RPG',
    'action rpg': 'RPG',
    'survival horror': 'Horror',
    'zombis': 'Horror',
    'zombies': 'Horror',
    'zombie': 'Horror',
    'psicologico': 'Horror',
    'rts': 'Estrategia',
    'gran estrategia': 'Estrategia',
    'tactica por turnos': 'Estrategia',
    'estrategia por turnos': 'Estrategia',
    '4x': 'Estrategia',
    'cozy': 'Casual',
    'acogedor': 'Casual',
    'acogedores': 'Casual',
    'relajado': 'Casual',
    'exploracion': 'Aventura',
    'explorar': 'Aventura',
    'exploration': 'Aventura',
    'misterio': 'Aventura',
    'tirador': 'FPS',
    'disparos tercera persona': 'FPS',
    'disparos primera persona': 'FPS',
}
